apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`ead.srv02.tce.ma.gov.br`) && Headers (`Userkey`, `teste`)
    kind: Rule
    services:
    - name: simple-api
      port: 3000
